[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "PUBLIC_*"

[test]
preload = ["./test/setup.ts"]
coverage = true
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["test/**"]
coverageThreshold = { line = 1, function = 1, statement = 1 }
